name: movie_search_assistant
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'


dependencies:
  generated:
    path: ./generated/
  get: ^4.7.2
  dio: ^5.8.0+1
  shared_preferences: ^2.5.3
  cached_network_image: ^3.4.1
  
  built_collection: ^5.1.1
  openapi_generator_annotations: ^6.1.0
  flutter_screenutil: ^5.9.3
  flutter:
    sdk: flutter

  
  cupertino_icons: ^1.0.8

dev_dependencies:
  build_runner: ^2.4.6
  openapi_generator: ^6.1.0
  openapi_generator_cli: ^6.1.0
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

